
DROP TABLE IF EXISTS CACHE;

DROP TABLE IF EXISTS FIBONACCI;

CREATE TABLE IF NOT EXISTS CACHE
(
    cache_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    method_key VARCHAR(200) NOT NULL,
    value BLOB(10000)
);

CREATE TABLE IF NOT EXISTS FIBONACCI
(
    fibonacci_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    number INT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_ID ON FIBONACHCHI(fibonacci_id);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_CACHE ON CACHE(method_key);
